{'plan_code': 'GjWawEh', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': 'GjWawEh', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
nohup: ignoring input
{'plan_code': '1a9HoRu', 'user_email': 'dongzhsh@genomics.cn'}
{'plan_code': 'OEQTsIj', 'user_email': 'zhangqianqian@genomics.cn'}
{'plan_code': 'OEQTsIj', 'user_email': 'zhangqianqian@genomics.cn'}
{'plan_code': 'OEQTsIj', 'user_email': 'zhangqianqian@genomics.cn'}
{'plan_code': 'OEQTsIj', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': '1hqAZbv', 'user_email': 'zhangqianqian@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
qC5reLC_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SacyM
Could not find a project named '16SacyM'
16SacyM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SacyM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 914e80b3-4006-4044-a892-70f1bcb5ff35:/1a9HoRu20201110141157
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/1a9HoRu/result/upload 914e80b3-4006-4044-a892-70f1bcb5ff35:/1a9HoRu20201110141157/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p qC5reLC_Online1 -d 90 575512829_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 914e80b3-4006-4044-a892-70f1bcb5ff35 575512829_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
yDDYIS3s4Sm_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BOVssoM
Could not find a project named 'BOVssoM'
BOVssoM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BOVssoM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir bcec63ff-ae59-4217-8b13-ef58b6d5a058:/1hqAZbv20201110141157
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/1hqAZbv/result/upload bcec63ff-ae59-4217-8b13-ef58b6d5a058:/1hqAZbv20201110141157/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p yDDYIS3s4Sm_Online1 -d 90 1036824528_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p bcec63ff-ae59-4217-8b13-ef58b6d5a058 1036824528_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RDrin2D5_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACppwM
Could not find a project named 'BACppwM'
BACppwM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACppwM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir d7665919-2c8b-4331-b27b-d4f8353dc5b4:/OEQTsIj20201110141157
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/OEQTsIj/result/upload d7665919-2c8b-4331-b27b-d4f8353dc5b4:/OEQTsIj20201110141157/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RDrin2D5_Online1 -d 90 lijunqiangcool_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p d7665919-2c8b-4331-b27b-d4f8353dc5b4 lijunqiangcool_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RDrin2D5_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACppwM
Could not find a project named 'BACppwM'
BACppwM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACppwM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir a1714e76-589a-44bf-895e-4646c1f8cdaa:/OEQTsIj20201110141157
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/OEQTsIj/result/upload a1714e76-589a-44bf-895e-4646c1f8cdaa:/OEQTsIj20201110141157/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RDrin2D5_Online1 -d 90 lijunqiangcool_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p a1714e76-589a-44bf-895e-4646c1f8cdaa lijunqiangcool_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RDrin2D5_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACppwM
Could not find a project named 'BACppwM'
BACppwM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACppwM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir d51e4886-133f-4bab-809d-d42567dbad3a:/OEQTsIj20201110141157
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/OEQTsIj/result/upload d51e4886-133f-4bab-809d-d42567dbad3a:/OEQTsIj20201110141157/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RDrin2D5_Online1 -d 90 lijunqiangcool_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p d51e4886-133f-4bab-809d-d42567dbad3a lijunqiangcool_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RDrin2D5_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACppwM
Could not find a project named 'BACppwM'
BACppwM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACppwM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 8f80ce26-f2ba-4ef3-86c3-8b7e4c36a5da:/OEQTsIj20201110141157
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/OEQTsIj/result/upload 8f80ce26-f2ba-4ef3-86c3-8b7e4c36a5da:/OEQTsIj20201110141157/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RDrin2D5_Online1 -d 90 lijunqiangcool_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 8f80ce26-f2ba-4ef3-86c3-8b7e4c36a5da lijunqiangcool_Online1 dv
{'plan_code': '5IdoL2v', 'user_email': 'dongzhsh@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
lkh5ZCy_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SufyM
Could not find a project named '16SufyM'
16SufyM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SufyM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir a44139e0-58f5-4720-814f-7173ce774bc7:/5IdoL2v20201110173304
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/5IdoL2v/result/upload a44139e0-58f5-4720-814f-7173ce774bc7:/5IdoL2v20201110173304/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p lkh5ZCy_Online1 -d 90 luzhaoyu111_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p a44139e0-58f5-4720-814f-7173ce774bc7 luzhaoyu111_Online1 dv
{'plan_code': 'sKivGQA', 'user_email': 'zhangnandi@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
0RyLytKUdL5_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICkevM
Could not find a project named 'MICkevM'
MICkevM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MICkevM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 73ad9203-a30b-45e6-a69f-236881aa1d8f:/sKivGQA20201113112006
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/sKivGQA/result/upload 73ad9203-a30b-45e6-a69f-236881aa1d8f:/sKivGQA20201113112006/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 0RyLytKUdL5_Online1 -d 90 852863346_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 73ad9203-a30b-45e6-a69f-236881aa1d8f 852863346_Online1 dv
{'plan_code': 'GVlhkOi', 'user_email': 'zhangqianqian@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
4l1HIB9_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACohzM_BACucuM
Could not find a project named 'BACohzM_BACucuM'
BACohzM_BACucuM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACohzM_BACucuM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 79cb885e-b338-4569-8807-a8cd193c04c7:/GVlhkOi20201113155159
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/GVlhkOi/result/upload 79cb885e-b338-4569-8807-a8cd193c04c7:/GVlhkOi20201113155159/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 4l1HIB9_Online1 -d 90 1799518909_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 79cb885e-b338-4569-8807-a8cd193c04c7 1799518909_Online1 dv
{'plan_code': 'wWNuoe4', 'user_email': 'zhangnandi@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
hnwYRDpc_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MUSatrM
Could not find a project named 'MUSatrM'
MUSatrM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MUSatrM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir e58cd11d-04ba-4854-bf09-9c53587abd95:/wWNuoe420201116162517
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/wWNuoe4/result/upload e58cd11d-04ba-4854-bf09-9c53587abd95:/wWNuoe420201116162517/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p hnwYRDpc_Online1 -d 90 875998258_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p e58cd11d-04ba-4854-bf09-9c53587abd95 875998258_Online1 dv
{'plan_code': 'GYqo9fv', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': 'THLCBBA', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
YjDfzkW_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select FUNwczM
Could not find a project named 'FUNwczM'
FUNwczM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project FUNwczM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 5d6e5d05-9816-447f-87e3-a1bedd9cee0a:/GYqo9fv20201118101203
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/GYqo9fv/result/upload 5d6e5d05-9816-447f-87e3-a1bedd9cee0a:/GYqo9fv20201118101203/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p YjDfzkW_Online1 -d 90 304508597_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 5d6e5d05-9816-447f-87e3-a1bedd9cee0a 304508597_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
YjDfzkW_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACdcfM
Could not find a project named 'BACdcfM'
BACdcfM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACdcfM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir e775b69c-7176-4c87-a006-0aa0e23fe208:/THLCBBA20201118101229
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/THLCBBA/result/upload e775b69c-7176-4c87-a006-0aa0e23fe208:/THLCBBA20201118101229/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p YjDfzkW_Online1 -d 90 304508597_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p e775b69c-7176-4c87-a006-0aa0e23fe208 304508597_Online1 dv
{'plan_code': 'JsKu70p', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
YjDfzkW_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select DISdgwM_DISsigM
Could not find a project named 'DISdgwM_DISsigM'
DISdgwM_DISsigM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project DISdgwM_DISsigM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 5a51d42f-2f78-4f09-8ba2-921ec2e45412:/JsKu70p20201118101303
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/JsKu70p/result/upload 5a51d42f-2f78-4f09-8ba2-921ec2e45412:/JsKu70p20201118101303/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p YjDfzkW_Online1 -d 90 304508597_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 5a51d42f-2f78-4f09-8ba2-921ec2e45412 304508597_Online1 dv
{'plan_code': 'vfctnv4', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': 'y9R4aOF', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': 'iqnrUi7', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
YjDfzkW_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select DISquoM
Could not find a project named 'DISquoM'
DISquoM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project DISquoM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 0c9e6673-7f15-40e0-a601-2e199ed22cc8:/vfctnv420201118102321
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/vfctnv4/result/upload 0c9e6673-7f15-40e0-a601-2e199ed22cc8:/vfctnv420201118102321/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p YjDfzkW_Online1 -d 90 304508597_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 0c9e6673-7f15-40e0-a601-2e199ed22cc8 304508597_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
YjDfzkW_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select DISquoM
Setting current project to: DISquoM
DISquoM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 0c9e6673-7f15-40e0-a601-2e199ed22cc8:/y9R4aOF20201118102330
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/y9R4aOF/result/upload 0c9e6673-7f15-40e0-a601-2e199ed22cc8:/y9R4aOF20201118102330/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p YjDfzkW_Online1 -d 90 304508597_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 0c9e6673-7f15-40e0-a601-2e199ed22cc8 304508597_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
YjDfzkW_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select DISquoM
Setting current project to: DISquoM
DISquoM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 0c9e6673-7f15-40e0-a601-2e199ed22cc8:/iqnrUi720201118102335
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/iqnrUi7/result/upload 0c9e6673-7f15-40e0-a601-2e199ed22cc8:/iqnrUi720201118102335/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p YjDfzkW_Online1 -d 90 304508597_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 0c9e6673-7f15-40e0-a601-2e199ed22cc8 304508597_Online1 dv
{'plan_code': '04oV5Yd', 'user_email': 'shijiamei@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
1yyWbtu_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3pgkM
Setting current project to: V3pgkM
V3pgkM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 15e50c64-0a99-4120-a818-89d4306ec0e4:/04oV5Yd20201118165258
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/04oV5Yd/result/upload 15e50c64-0a99-4120-a818-89d4306ec0e4:/04oV5Yd20201118165258/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 1yyWbtu_Online1 -d 90 439256799_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 15e50c64-0a99-4120-a818-89d4306ec0e4 439256799_Online1 dv
{'plan_code': 'ZK4pAPc', 'user_email': 'shijiamei@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
kHaHCjS_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3vjbM
Could not find a project named 'V3vjbM'
V3vjbM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project V3vjbM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 689649e9-0e51-422c-8bd0-4984bbbf6cdd:/ZK4pAPc20201118170506
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/ZK4pAPc/result/upload 689649e9-0e51-422c-8bd0-4984bbbf6cdd:/ZK4pAPc20201118170506/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p kHaHCjS_Online1 -d 90 11816039_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 689649e9-0e51-422c-8bd0-4984bbbf6cdd 11816039_Online1 dv
{'plan_code': 'i2zuj2c', 'user_email': 'shijiamei@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
1yyWbtu_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select ITSoxlM
Setting current project to: ITSoxlM
ITSoxlM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir a8d12a28-3bb9-4da3-9ee0-c8720fc6d453:/i2zuj2c20201119142252
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/i2zuj2c/result/upload a8d12a28-3bb9-4da3-9ee0-c8720fc6d453:/i2zuj2c20201119142252/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 1yyWbtu_Online1 -d 90 439256799_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p a8d12a28-3bb9-4da3-9ee0-c8720fc6d453 439256799_Online1 dv
{'plan_code': 'bbxxzVk', 'user_email': 'zhangnandi@genomics.cn'}
{'plan_code': 'xGYNO9v', 'user_email': 'zhangnandi@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
uuqYCfu_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select TICpbxM
Could not find a project named 'TICpbxM'
TICpbxM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project TICpbxM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 35279360-5a6f-4e92-8deb-334fb859c76e:/bbxxzVk20201119170441
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/bbxxzVk/result/upload 35279360-5a6f-4e92-8deb-334fb859c76e:/bbxxzVk20201119170441/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p uuqYCfu_Online1 -d 90 haoqin_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 35279360-5a6f-4e92-8deb-334fb859c76e haoqin_Online1 dv
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
uuqYCfu_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select TICpbxM
Setting current project to: TICpbxM
TICpbxM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 35279360-5a6f-4e92-8deb-334fb859c76e:/xGYNO9v20201119170447
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/xGYNO9v/result/upload 35279360-5a6f-4e92-8deb-334fb859c76e:/xGYNO9v20201119170447/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p uuqYCfu_Online1 -d 90 haoqin_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 35279360-5a6f-4e92-8deb-334fb859c76e haoqin_Online1 dv
{'plan_code': 'nF7jV3X', 'user_email': 'dongzhsh@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
UohxRJAV7Gb_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SqmoM
Could not find a project named '16SqmoM'
16SqmoM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SqmoM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir cb2e14f2-f81c-4ccf-9c06-92e15b054b51:/nF7jV3X20201119181654
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/nF7jV3X/result/upload cb2e14f2-f81c-4ccf-9c06-92e15b054b51:/nF7jV3X20201119181654/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p UohxRJAV7Gb_Online1 -d 90 377414852_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p cb2e14f2-f81c-4ccf-9c06-92e15b054b51 377414852_Online1 dv
{'plan_code': '2hoAPgX', 'user_email': 'zhangqianqian@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
fM5CeJHA_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACraeM
Could not find a project named 'BACraeM'
BACraeM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACraeM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 134e8406-13d8-4e1d-be42-1f6c3126e86f:/2hoAPgX20201120110703
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/2hoAPgX/result/upload 134e8406-13d8-4e1d-be42-1f6c3126e86f:/2hoAPgX20201120110703/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p fM5CeJHA_Online1 -d 90 fight23455556_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 134e8406-13d8-4e1d-be42-1f6c3126e86f fight23455556_Online1 dv
{'plan_code': 'YBYZ7Ka', 'user_email': 'zhangnandi@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
0RyLytKUdL5_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICpjjM
Could not find a project named 'MICpjjM'
MICpjjM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MICpjjM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir ad3ee6cc-f3d2-4506-8d32-fa6a3517ee17:/YBYZ7Ka20201121103206
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/YBYZ7Ka/result/upload ad3ee6cc-f3d2-4506-8d32-fa6a3517ee17:/YBYZ7Ka20201121103206/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 0RyLytKUdL5_Online1 -d 90 852863346_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p ad3ee6cc-f3d2-4506-8d32-fa6a3517ee17 852863346_Online1 dv
{'plan_code': 'QfVt2Db', 'user_email': 'dongzhsh@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
9p7Hewe_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SxnkM
Could not find a project named '16SxnkM'
16SxnkM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SxnkM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir d863e973-fcd8-40cc-ad9d-01cb5d007fb9:/QfVt2Db20201123131008
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/QfVt2Db/result/upload d863e973-fcd8-40cc-ad9d-01cb5d007fb9:/QfVt2Db20201123131008/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 9p7Hewe_Online1 -d 90 ye_linsen_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p d863e973-fcd8-40cc-ad9d-01cb5d007fb9 ye_linsen_Online1 dv
{'plan_code': 'aebM7kC', 'user_email': 'dongzhsh@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
JlXEyQe_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SbwgM_16SadrM
Could not find a project named '16SbwgM_16SadrM'
16SbwgM_16SadrM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SbwgM_16SadrM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 8a74a649-82dc-4591-b214-fc5fc0aa32a4:/aebM7kC20201123143814
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/aebM7kC/result/upload 8a74a649-82dc-4591-b214-fc5fc0aa32a4:/aebM7kC20201123143814/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p JlXEyQe_Online1 -d 90 yuli-1220_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 8a74a649-82dc-4591-b214-fc5fc0aa32a4 yuli-1220_Online1 dv
{'plan_code': 'vRGje0E', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
n9ZG56x_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3pprM
Could not find a project named 'V3pprM'
V3pprM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project V3pprM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir d05168b8-c816-439b-a69a-afb9ba9baabb:/vRGje0E20201123175828
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/vRGje0E/result/upload d05168b8-c816-439b-a69a-afb9ba9baabb:/vRGje0E20201123175828/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p n9ZG56x_Online1 -d 90 gaolu755243_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p d05168b8-c816-439b-a69a-afb9ba9baabb gaolu755243_Online1 dv
{'plan_code': 'ubfEySn', 'user_email': 'fengaiqin@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
sM40m2e0_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICtpiM
Could not find a project named 'MICtpiM'
MICtpiM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MICtpiM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir d27a1e70-ef02-4b18-850f-ac274db47273:/ubfEySn20201124085149
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/ubfEySn/result/upload d27a1e70-ef02-4b18-850f-ac274db47273:/ubfEySn20201124085149/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p sM40m2e0_Online1 -d 90 wb765198_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p d27a1e70-ef02-4b18-850f-ac274db47273 wb765198_Online1 dv
{'plan_code': 'fMFY5mC', 'user_email': 'fengaiqin@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
VTWdDcc3i4_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select ANOgzxM
Could not find a project named 'ANOgzxM'
ANOgzxM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project ANOgzxM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir cf34094d-fd11-4eb8-a1ed-cc792789cae6:/fMFY5mC20201125091633
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/fMFY5mC/result/upload cf34094d-fd11-4eb8-a1ed-cc792789cae6:/fMFY5mC20201125091633/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p VTWdDcc3i4_Online1 -d 90 892035137_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p cf34094d-fd11-4eb8-a1ed-cc792789cae6 892035137_Online1 dv
{'plan_code': '8SOaWQs', 'user_email': 'zhoudandan@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
sMHH2NVxP0_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METsnpM
Could not find a project named 'METsnpM'
METsnpM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project METsnpM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir bc307673-06bc-4fa2-adf4-c027dfce9201:/8SOaWQs20201125103414
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/8SOaWQs/result/upload bc307673-06bc-4fa2-adf4-c027dfce9201:/8SOaWQs20201125103414/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p sMHH2NVxP0_Online1 -d 90 2018102052_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p bc307673-06bc-4fa2-adf4-c027dfce9201 2018102052_Online1 dv
{'plan_code': 'wyH68up', 'user_email': 'zhangqianqian@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
QTPQdg0Of_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACixwM_BACcnlM_BACahsM
Could not find a project named 'BACixwM_BACcnlM_BACahsM'
BACixwM_BACcnlM_BACahsM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACixwM_BACcnlM_BACahsM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir f664cf6a-65fc-4340-a954-cd28b486710a:/wyH68up20201125140858
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/wyH68up/result/upload f664cf6a-65fc-4340-a954-cd28b486710a:/wyH68up20201125140858/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p QTPQdg0Of_Online1 -d 90 1765688164_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p f664cf6a-65fc-4340-a954-cd28b486710a 1765688164_Online1 dv
{'plan_code': 'xsnPZe1', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
L7AIYgG_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select SHExatM
Could not find a project named 'SHExatM'
SHExatM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project SHExatM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 858019d4-c036-49d8-b05f-47004c6787a1:/xsnPZe120201125163022
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/xsnPZe1/result/upload 858019d4-c036-49d8-b05f-47004c6787a1:/xsnPZe120201125163022/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p L7AIYgG_Online1 -d 90 yzhao818_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 858019d4-c036-49d8-b05f-47004c6787a1 yzhao818_Online1 dv
{'plan_code': 'SwxEe9Q', 'user_email': 'zhoudandan@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
kacKB0D_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METikaM
Could not find a project named 'METikaM'
METikaM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project METikaM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 070bd88b-9b94-48ad-8304-405433e1b9a0:/SwxEe9Q20201126153737
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/SwxEe9Q/result/upload 070bd88b-9b94-48ad-8304-405433e1b9a0:/SwxEe9Q20201126153737/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p kacKB0D_Online1 -d 90 404668852_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 070bd88b-9b94-48ad-8304-405433e1b9a0 404668852_Online1 dv
nohup: ignoring input
{'plan_code': 'B4eSXve', 'user_email': 'zhoudandan@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
Process Process-1:
Traceback (most recent call last):
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 47, in baseinfo_search
    self.usrmd5()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 61, in usrmd5
    mb.update(self.usremail.encode('utf8'))
AttributeError: 'Pipeline_Upload' object has no attribute 'usremail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': 'B4eSXve', 'user_email': 'zhoudandan@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
Process Process-2:
Traceback (most recent call last):
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 47, in baseinfo_search
    self.usrmd5()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 61, in usrmd5
    mb.update(self.usremail.encode('utf8'))
AttributeError: 'Pipeline_Upload' object has no attribute 'usremail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '1zphvEZ', 'user_email': 'zhoudandan@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
Process Process-3:
Traceback (most recent call last):
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 47, in baseinfo_search
    self.usrmd5()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 61, in usrmd5
    mb.update(self.usremail.encode('utf8'))
AttributeError: 'Pipeline_Upload' object has no attribute 'usremail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': 'YjQigU5', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
Process Process-4:
Traceback (most recent call last):
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 47, in baseinfo_search
    self.usrmd5()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 61, in usrmd5
    mb.update(self.usremail.encode('utf8'))
AttributeError: 'Pipeline_Upload' object has no attribute 'usremail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': 'B4eSXve', 'user_email': 'zhoudandan@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
Process Process-5:
Traceback (most recent call last):
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 47, in baseinfo_search
    self.usrmd5()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 61, in usrmd5
    mb.update(self.usremail.encode('utf8'))
AttributeError: 'Pipeline_Upload' object has no attribute 'usremail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': 'B4eSXve', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
Process Process-6:
Traceback (most recent call last):
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 47, in baseinfo_search
    self.usrmd5()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 61, in usrmd5
    mb.update(self.usremail.encode('utf8'))
AttributeError: 'Pipeline_Upload' object has no attribute 'usremail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': 'YjQigU5', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:BgiMicrobe%402020@120.24.55.116:27017
connect mongo successful......
connect mysql......
connect mysql successful......
Process Process-7:
Traceback (most recent call last):
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 47, in baseinfo_search
    self.usrmd5()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 61, in usrmd5
    mb.update(self.usremail.encode('utf8'))
AttributeError: 'Pipeline_Upload' object has no attribute 'usremail'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/root/16s/Modules/Bo_upload/run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 67, in <module>
    rab.receieve()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 81, in receieve
    self.channel.start_consuming()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.AMQPHeartbeatTimeout: No activity or too many missed heartbeats in the last 60 seconds
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 66, in <module>
    rab = MultiRabbit(exchange, queue, route)
  File "run_boupload.py", line 31, in __init__
    super(MultiRabbit, self).__init__(exchange, queue, routing_key)
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 23, in __init__
    self.init_connect()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 40, in init_connect
    self.connection = pika.BlockingConnection(pika.ConnectionParameters(MyRabbit.MQ_CONFIG['host'], MyRabbit.MQ_CONFIG['port'], MyRabbit.MQ_CONFIG['vhost'], credentials))
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 66, in <module>
    rab = MultiRabbit(exchange, queue, route)
  File "run_boupload.py", line 31, in __init__
    super(MultiRabbit, self).__init__(exchange, queue, routing_key)
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 23, in __init__
    self.init_connect()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 40, in init_connect
    self.connection = pika.BlockingConnection(pika.ConnectionParameters(MyRabbit.MQ_CONFIG['host'], MyRabbit.MQ_CONFIG['port'], MyRabbit.MQ_CONFIG['vhost'], credentials))
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 66, in <module>
    rab = MultiRabbit(exchange, queue, route)
  File "run_boupload.py", line 31, in __init__
    super(MultiRabbit, self).__init__(exchange, queue, routing_key)
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 23, in __init__
    self.init_connect()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 40, in init_connect
    self.connection = pika.BlockingConnection(pika.ConnectionParameters(MyRabbit.MQ_CONFIG['host'], MyRabbit.MQ_CONFIG['port'], MyRabbit.MQ_CONFIG['vhost'], credentials))
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 66, in <module>
    rab = MultiRabbit(exchange, queue, route)
  File "run_boupload.py", line 31, in __init__
    super(MultiRabbit, self).__init__(exchange, queue, routing_key)
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 23, in __init__
    self.init_connect()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 40, in init_connect
    self.connection = pika.BlockingConnection(pika.ConnectionParameters(MyRabbit.MQ_CONFIG['host'], MyRabbit.MQ_CONFIG['port'], MyRabbit.MQ_CONFIG['vhost'], credentials))
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 66, in <module>
    rab = MultiRabbit(exchange, queue, route)
  File "run_boupload.py", line 31, in __init__
    super(MultiRabbit, self).__init__(exchange, queue, routing_key)
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 23, in __init__
    self.init_connect()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 40, in init_connect
    self.connection = pika.BlockingConnection(pika.ConnectionParameters(MyRabbit.MQ_CONFIG['host'], MyRabbit.MQ_CONFIG['port'], MyRabbit.MQ_CONFIG['vhost'], credentials))
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 66, in <module>
    rab = MultiRabbit(exchange, queue, route)
  File "run_boupload.py", line 31, in __init__
    super(MultiRabbit, self).__init__(exchange, queue, routing_key)
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 23, in __init__
    self.init_connect()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 40, in init_connect
    self.connection = pika.BlockingConnection(pika.ConnectionParameters(MyRabbit.MQ_CONFIG['host'], MyRabbit.MQ_CONFIG['port'], MyRabbit.MQ_CONFIG['vhost'], credentials))
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 15, in <module>
    from Email.exchange_email import Exchange_email
  File "/root/16s/Modules_v2/Bo_upload/../Email/exchange_email.py", line 7, in <module>
    from lib.config import *
  File "/root/16s/Modules_v2/Bo_upload/../lib/config.py", line 25
    "port" : 5672,
           ^
SyntaxError: invalid syntax
nohup: ignoring input
{'plan_code': 'RxUQNrD', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-1:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '31UlyPn', 'user_email': 'shijiamei@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-2:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '5Z6iGqZ', 'user_email': 'dongzhsh@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-3:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-4:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '0wYBb53', 'user_email': 'fengaiqin@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-5:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-6:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-7:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-8:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-9:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@120.24.55.116:27017
connect mongo successful......
Process Process-10:
Traceback (most recent call last):
  File "run_boupload.py", line 46, in Run_mainpipe
    myupload = Pipeline_Upload(message['plan_code'])
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 28, in __init__
    self.baseinfo_search()
  File "/root/16s/Modules_v2/Bo_upload/delivery_upload.py", line 36, in baseinfo_search
    self.baseinfo = Configuration(self.analysisid, self.upload_dir)
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 27, in __init__
    self.search_mongo()
  File "/root/16s/Modules_v2/Bo_upload/../Bo_upload/Baseconfiguration.py", line 56, in search_mongo
    findinfo = collection.find_one({'planCode': self.analysisid})
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/collection.py", line 1273, in find_one
    for result in cursor.limit(-1):
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1807, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1760, in __start_session
    server_session = self._get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1793, in _get_server_session
    return self._topology.get_server_session()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 477, in get_server_session
    None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 120.24.55.116:27017: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/Software/miniconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "run_boupload.py", line 53, in Run_mainpipe
    Exchange_email(message['plan_code'] + " Micro16S Auto Delivery Debug", errlog, error_to_adress['error_to_adress'], message['user_email'])
NameError: name 'error_to_adress' is not defined
nohup: ignoring input
Traceback (most recent call last):
  File "run_boupload.py", line 67, in <module>
    rab.receieve()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 81, in receieve
    self.channel.start_consuming()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 513, in _flush_output
    self._impl.ioloop.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 576, in poll
    self._poller.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1181, in poll
    events = self._poll.poll(self._get_max_wait())
KeyboardInterrupt
nohup: ignoring input
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@16s2:27017
connect mongo successful......
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@16s2:27017
connect mongo successful......
{'plan_code': '5vZ281Q', 'user_email': 'shijiamei@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@16s2:27017
connect mongo successful......
{'plan_code': '31UlyPn', 'user_email': 'shijiamei@genomics.cn'}
mongodb://root:SZ%40Micro.system2021@16s2:27017
connect mongo successful......
nohup: ignoring input
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
mongodb://root:SZ%40Micro.system2021@16s2:27017
connect mongo successful......
Traceback (most recent call last):
  File "run_boupload.py", line 67, in <module>
    rab.receieve()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 81, in receieve
    self.channel.start_consuming()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 513, in _flush_output
    self._impl.ioloop.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 576, in poll
    self._poller.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1181, in poll
    events = self._poll.poll(self._get_max_wait())
KeyboardInterrupt
nohup: ignoring input
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
mongodb://root:SZ%40Micro.system2021@16s2:27017
connect mongo successful......
Traceback (most recent call last):
  File "run_boupload.py", line 67, in <module>
    rab.receieve()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 81, in receieve
    self.channel.start_consuming()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 513, in _flush_output
    self._impl.ioloop.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 576, in poll
    self._poller.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1181, in poll
    events = self._poll.poll(self._get_max_wait())
KeyboardInterrupt
nohup: ignoring input
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:SZ%40Micro.system2021@16s2:27017
connect mongo successful......
nohup: ignoring input
{'plan_code': '31UlyPn', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
JpCY3126zoT_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3VirrM
Could not find a project named 'V3VirrM'
V3VirrM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project V3VirrM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir de176a55-2698-46b0-8ef3-465841863dd5:/31UlyPn20201208160319
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/31UlyPn/result/upload de176a55-2698-46b0-8ef3-465841863dd5:/31UlyPn20201208160319/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p JpCY3126zoT_Online1 -d 90 163846D841F7Aff061815A251783Cf72
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p de176a55-2698-46b0-8ef3-465841863dd5 163846D841F7Aff061815A251783Cf72 dv
{'plan_code': '5vZ281Q', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
VqVBJ3pkM_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select ITSopdM
Could not find a project named 'ITSopdM'
ITSopdM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project ITSopdM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir e001f5f7-bdc3-4a40-8496-0845f71c99c5:/5vZ281Q20201208174805
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/5vZ281Q/result/upload e001f5f7-bdc3-4a40-8496-0845f71c99c5:/5vZ281Q20201208174805/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p VqVBJ3pkM_Online1 -d 90 1Ed7370252Dcdf54737618A4A466B45E
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p e001f5f7-bdc3-4a40-8496-0845f71c99c5 1Ed7370252Dcdf54737618A4A466B45E dv
{'plan_code': 'HtlCQt9', 'user_email': 'zhoudandan@genomics.cn'}
{'plan_code': 'JrNK2Ak', 'user_email': 'zhoudandan@genomics.cn'}
{'plan_code': '5eTzXHM', 'user_email': 'zhoudandan@genomics.cn'}
{'plan_code': '4BxLKR7', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
2g4DN2Ql5S_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select SOIkksM
Could not find a project named 'SOIkksM'
SOIkksM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project SOIkksM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 038d9001-1fc0-4dea-a65c-ce811428076d:/HtlCQt920201208181330
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/HtlCQt9/result/upload 038d9001-1fc0-4dea-a65c-ce811428076d:/HtlCQt920201208181330/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 2g4DN2Ql5S_Online1 -d 90 532E40Ea63F04523888Ae8Cd5F6A059B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 038d9001-1fc0-4dea-a65c-ce811428076d 532E40Ea63F04523888Ae8Cd5F6A059B dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
2g4DN2Ql5S_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select SOIcgtM
Could not find a project named 'SOIcgtM'
SOIcgtM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project SOIcgtM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 89bf287f-9be6-40c0-9171-c1d7fa863a8e:/4BxLKR720201208181506
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/4BxLKR7/result/upload 89bf287f-9be6-40c0-9171-c1d7fa863a8e:/4BxLKR720201208181506/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 2g4DN2Ql5S_Online1 -d 90 532E40Ea63F04523888Ae8Cd5F6A059B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 89bf287f-9be6-40c0-9171-c1d7fa863a8e 532E40Ea63F04523888Ae8Cd5F6A059B dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
2g4DN2Ql5S_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select SOIkksM
Setting current project to: SOIkksM
SOIkksM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 038d9001-1fc0-4dea-a65c-ce811428076d:/JrNK2Ak20201208181341
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/JrNK2Ak/result/upload 038d9001-1fc0-4dea-a65c-ce811428076d:/JrNK2Ak20201208181341/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 2g4DN2Ql5S_Online1 -d 90 532E40Ea63F04523888Ae8Cd5F6A059B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 038d9001-1fc0-4dea-a65c-ce811428076d 532E40Ea63F04523888Ae8Cd5F6A059B dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
2g4DN2Ql5S_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select SOIkksM
Setting current project to: SOIkksM
SOIkksM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 038d9001-1fc0-4dea-a65c-ce811428076d:/5eTzXHM20201208181346
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/5eTzXHM/result/upload 038d9001-1fc0-4dea-a65c-ce811428076d:/5eTzXHM20201208181346/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 2g4DN2Ql5S_Online1 -d 90 532E40Ea63F04523888Ae8Cd5F6A059B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 038d9001-1fc0-4dea-a65c-ce811428076d 532E40Ea63F04523888Ae8Cd5F6A059B dv
{'plan_code': 'HovnKOc', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
4sbLBBMCUbG_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select PROpokM
Could not find a project named 'PROpokM'
PROpokM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project PROpokM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 94d35223-93cb-4864-b104-8e4888a8b727:/HovnKOc20201209085608
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/HovnKOc/result/upload 94d35223-93cb-4864-b104-8e4888a8b727:/HovnKOc20201209085608/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 4sbLBBMCUbG_Online1 -d 90 Edaec7037D7F40Df34Dae7001Eb77C49
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 94d35223-93cb-4864-b104-8e4888a8b727 Edaec7037D7F40Df34Dae7001Eb77C49 dv
{'plan_code': '0wYBb53', 'user_email': 'fengaiqin@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
nE32vqA_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICfemM
Could not find a project named 'MICfemM'
MICfemM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MICfemM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 23513796-ebf4-431a-9033-572403ed40c8:/0wYBb5320201209085952
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/0wYBb53/result/upload 23513796-ebf4-431a-9033-572403ed40c8:/0wYBb5320201209085952/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p nE32vqA_Online1 -d 90 E2B8030288F814C4C6Ac0Dc26Fa76C67
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 23513796-ebf4-431a-9033-572403ed40c8 E2B8030288F814C4C6Ac0Dc26Fa76C67 dv
{'plan_code': 'qeH7fEj', 'user_email': 'fengaiqin@genomics.cn'}
{'plan_code': 'qeH7fEj', 'user_email': 'fengaiqin@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
fiUAgLec_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICcojM_MICgseM
Could not find a project named 'MICcojM_MICgseM'
MICcojM_MICgseM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MICcojM_MICgseM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir ba32d851-f0a4-4fa9-b80b-3e76009c5d6a:/qeH7fEj20201209092330
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/qeH7fEj/result/upload ba32d851-f0a4-4fa9-b80b-3e76009c5d6a:/qeH7fEj20201209092330/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p fiUAgLec_Online1 -d 90 E2D664293887C3Fca160E0E3B8A5921B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p ba32d851-f0a4-4fa9-b80b-3e76009c5d6a E2D664293887C3Fca160E0E3B8A5921B dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
fiUAgLec_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICcojM_MICgseM
Setting current project to: MICcojM_MICgseM
MICcojM_MICgseM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir ba32d851-f0a4-4fa9-b80b-3e76009c5d6a:/qeH7fEj20201209092347
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/qeH7fEj/result/upload ba32d851-f0a4-4fa9-b80b-3e76009c5d6a:/qeH7fEj20201209092347/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p fiUAgLec_Online1 -d 90 E2D664293887C3Fca160E0E3B8A5921B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p ba32d851-f0a4-4fa9-b80b-3e76009c5d6a E2D664293887C3Fca160E0E3B8A5921B dv
{'plan_code': 'sIsY2OG', 'user_email': 'fengaiqin@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
Y4On2NF_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICwkeM
Could not find a project named 'MICwkeM'
MICwkeM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MICwkeM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 9fa8cf1c-bfc9-427d-94d8-7c704257278f:/sIsY2OG20201209093933
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/sIsY2OG/result/upload 9fa8cf1c-bfc9-427d-94d8-7c704257278f:/sIsY2OG20201209093933/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p Y4On2NF_Online1 -d 90 6557F9773F7F8E085B136A3114E702Ba
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 9fa8cf1c-bfc9-427d-94d8-7c704257278f 6557F9773F7F8E085B136A3114E702Ba dv
{'plan_code': '5Z6iGqZ', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
KRSsR7j_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SestM
Could not find a project named '16SestM'
16SestM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SestM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir c351b7a0-a157-4803-82d0-2a6f628f8a5e:/5Z6iGqZ20201209100059
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/5Z6iGqZ/result/upload c351b7a0-a157-4803-82d0-2a6f628f8a5e:/5Z6iGqZ20201209100059/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p KRSsR7j_Online1 -d 90 2D436150623248738Eb9Acde9A713084
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p c351b7a0-a157-4803-82d0-2a6f628f8a5e 2D436150623248738Eb9Acde9A713084 dv
{'plan_code': '6N0tdtU', 'user_email': 'shijiamei@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
VqVBJ3pkM_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3VkhyM
Could not find a project named 'V3VkhyM'
V3VkhyM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project V3VkhyM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 7cb57b0a-a468-4bdb-ad23-c9739693cb69:/6N0tdtU20201209144437
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/6N0tdtU/result/upload 7cb57b0a-a468-4bdb-ad23-c9739693cb69:/6N0tdtU20201209144437/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p VqVBJ3pkM_Online1 -d 90 1Ed7370252Dcdf54737618A4A466B45E
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 7cb57b0a-a468-4bdb-ad23-c9739693cb69 1Ed7370252Dcdf54737618A4A466B45E dv
{'plan_code': 'h2lQuFb', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
SO3YPAaIt0R_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select RATyrhM
Could not find a project named 'RATyrhM'
RATyrhM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project RATyrhM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir e885ada5-6df6-429f-8d2e-fe75b3189804:/h2lQuFb20201209155113
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/h2lQuFb/result/upload e885ada5-6df6-429f-8d2e-fe75b3189804:/h2lQuFb20201209155113/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p SO3YPAaIt0R_Online1 -d 90 72Bc917Acfbfec8554F6936C4D47950D
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p e885ada5-6df6-429f-8d2e-fe75b3189804 72Bc917Acfbfec8554F6936C4D47950D dv
{'plan_code': 'qyeVkeP', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
iR7Pxn8ps4z_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METlxqM_METvseM_V4ymvM2
Could not find a project named 'METlxqM_METvseM_V4ymvM2'
METlxqM_METvseM_V4ymvM2 need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project METlxqM_METvseM_V4ymvM2
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 625fcaaa-6de0-4d99-be3e-71517940741f:/qyeVkeP20201209160520
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/qyeVkeP/result/upload 625fcaaa-6de0-4d99-be3e-71517940741f:/qyeVkeP20201209160520/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p iR7Pxn8ps4z_Online1 -d 90 441E5217B898C3634Ee41969977018Ee
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 625fcaaa-6de0-4d99-be3e-71517940741f 441E5217B898C3634Ee41969977018Ee dv
{'plan_code': 'c4zLotZ', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
u8nBvmx4_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MUSvhzM
Could not find a project named 'MUSvhzM'
MUSvhzM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MUSvhzM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir ed003ba0-fb9b-485d-802a-9d13a389c948:/c4zLotZ20201209165630
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/c4zLotZ/result/upload ed003ba0-fb9b-485d-802a-9d13a389c948:/c4zLotZ20201209165630/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p u8nBvmx4_Online1 -d 90 Fc06A53544313323389F404B1Ccd02B9
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p ed003ba0-fb9b-485d-802a-9d13a389c948 Fc06A53544313323389F404B1Ccd02B9 dv
{'plan_code': '4hTusUq', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
u8nBvmx4_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MUSvhzM
Setting current project to: MUSvhzM
MUSvhzM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir ed003ba0-fb9b-485d-802a-9d13a389c948:/4hTusUq20201209171053
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/4hTusUq/result/upload ed003ba0-fb9b-485d-802a-9d13a389c948:/4hTusUq20201209171053/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p u8nBvmx4_Online1 -d 90 Fc06A53544313323389F404B1Ccd02B9
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p ed003ba0-fb9b-485d-802a-9d13a389c948 Fc06A53544313323389F404B1Ccd02B9 dv
{'plan_code': 'Y95tWHm', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
u8nBvmx4_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MUSvhzM
Setting current project to: MUSvhzM
MUSvhzM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir ed003ba0-fb9b-485d-802a-9d13a389c948:/Y95tWHm20201209180551
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/Y95tWHm/result/upload ed003ba0-fb9b-485d-802a-9d13a389c948:/Y95tWHm20201209180551/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p u8nBvmx4_Online1 -d 90 Fc06A53544313323389F404B1Ccd02B9
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p ed003ba0-fb9b-485d-802a-9d13a389c948 Fc06A53544313323389F404B1Ccd02B9 dv
{'plan_code': 'O56xsTY', 'user_email': 'fengaiqin@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
rnGkx5y_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select APRiccM_ANOgzxM
Could not find a project named 'APRiccM_ANOgzxM'
APRiccM_ANOgzxM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project APRiccM_ANOgzxM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir bc900cbb-079b-4394-86de-6079bc9e643c:/O56xsTY20201210092806
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/O56xsTY/result/upload bc900cbb-079b-4394-86de-6079bc9e643c:/O56xsTY20201210092806/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p rnGkx5y_Online1 -d 90 B976Fe401175854C0C60B595Dcfc2088
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p bc900cbb-079b-4394-86de-6079bc9e643c B976Fe401175854C0C60B595Dcfc2088 dv
{'plan_code': '2t7thfI', 'user_email': 'liangliping@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
5KLvbns1xtd_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SsvyM
Could not find a project named '16SsvyM'
16SsvyM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SsvyM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir e997b504-5e5e-4ce4-9230-73ce3737ea19:/2t7thfI20201210095258
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/2t7thfI/result/upload e997b504-5e5e-4ce4-9230-73ce3737ea19:/2t7thfI20201210095258/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 5KLvbns1xtd_Online1 -d 90 63C8666B2Fd095C9D0D5006D53Ae1D2F
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p e997b504-5e5e-4ce4-9230-73ce3737ea19 63C8666B2Fd095C9D0D5006D53Ae1D2F dv
{'plan_code': 'H9kfYcR', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
SO3YPAaIt0R_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select RATyrhM
Setting current project to: RATyrhM
RATyrhM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir e885ada5-6df6-429f-8d2e-fe75b3189804:/H9kfYcR20201210103620
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/H9kfYcR/result/upload e885ada5-6df6-429f-8d2e-fe75b3189804:/H9kfYcR20201210103620/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p SO3YPAaIt0R_Online1 -d 90 72Bc917Acfbfec8554F6936C4D47950D
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p e885ada5-6df6-429f-8d2e-fe75b3189804 72Bc917Acfbfec8554F6936C4D47950D dv
{'plan_code': 'xrHmZgp', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
FbLpMA73Q37_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METkwzM
Setting current project to: METkwzM
METkwzM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 70baaafb-fc32-4812-89bc-66c9076c0a13:/xrHmZgp20201210110433
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/xrHmZgp/result/upload 70baaafb-fc32-4812-89bc-66c9076c0a13:/xrHmZgp20201210110433/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p FbLpMA73Q37_Online1 -d 90 832E70Cc7231D55E316413D85F26E0Da
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 70baaafb-fc32-4812-89bc-66c9076c0a13 832E70Cc7231D55E316413D85F26E0Da dv
{'plan_code': 'JgMvBEy', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
i2PI4MYW_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SoqyM
Could not find a project named '16SoqyM'
16SoqyM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SoqyM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir de057caf-00b3-4947-aaaf-1005b13db304:/JgMvBEy20201210145638
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/JgMvBEy/result/upload de057caf-00b3-4947-aaaf-1005b13db304:/JgMvBEy20201210145638/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p i2PI4MYW_Online1 -d 90 Ef7C65C05Efffd8Fb5Acebad59E8160F
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p de057caf-00b3-4947-aaaf-1005b13db304 Ef7C65C05Efffd8Fb5Acebad59E8160F dv
{'plan_code': 'VcMJGx7', 'user_email': 'zhangqianqian@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
QTPQdg0Of_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACixwM_BACcnlM_BACahsM
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8a90a09150>: Failed to establish a new connection: [Errno 111] Connection refused',))
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8a90a09150>: Failed to establish a new connection: [Errno 111] Connection refused',))
bo updating... or Other error; Exit()
{'plan_code': '9xAe6Dw', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
wyGtHNoc_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SumxM
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7417657110>: Failed to establish a new connection: [Errno 111] Connection refused',))
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7417657110>: Failed to establish a new connection: [Errno 111] Connection refused',))
bo updating... or Other error; Exit()
{'plan_code': '9xAe6Dw', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
wyGtHNoc_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SumxM
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff074d36110>: Failed to establish a new connection: [Errno 111] Connection refused',))
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff074d36110>: Failed to establish a new connection: [Errno 111] Connection refused',))
bo updating... or Other error; Exit()
{'plan_code': 'QDlZ69x', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': '9xAe6Dw', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
wyGtHNoc_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SumxM
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f455be27110>: Failed to establish a new connection: [Errno 111] Connection refused',))
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f455be27110>: Failed to establish a new connection: [Errno 111] Connection refused',))
bo updating... or Other error; Exit()
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
wyGtHNoc_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SumxM
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb6b3a1110>: Failed to establish a new connection: [Errno 111] Connection refused',))
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 189, in APIRequest
    response = requests.request(method, url, verify=False, params=params, data=data, json=json, headers=headers, timeout=timeout, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='app.bgionline.cn', port=1001): Max retries exceeded with url: /api/project/project (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcb6b3a1110>: Failed to establish a new connection: [Errno 111] Connection refused',))
bo updating... or Other error; Exit()
{'plan_code': 'oHTjUti', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
kacKB0D_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METikaM
Setting current project to: METikaM
METikaM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 070bd88b-9b94-48ad-8304-405433e1b9a0:/oHTjUti20201211094004
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/oHTjUti/result/upload 070bd88b-9b94-48ad-8304-405433e1b9a0:/oHTjUti20201211094004/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p kacKB0D_Online1 -d 90 027B2Afd58Bb088Ee9B85E3A2Be1234C
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 070bd88b-9b94-48ad-8304-405433e1b9a0 027B2Afd58Bb088Ee9B85E3A2Be1234C dv
{'plan_code': 'lAaAYBC', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
J7N7gtXUDi_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SkamM
Could not find a project named '16SkamM'
16SkamM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SkamM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir d8241104-b62d-48d9-83b8-85e93110ea31:/lAaAYBC20201211115000
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/lAaAYBC/result/upload d8241104-b62d-48d9-83b8-85e93110ea31:/lAaAYBC20201211115000/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p J7N7gtXUDi_Online1 -d 90 65D980Dec24252Eacb190E5Ba9Dde4F1
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p d8241104-b62d-48d9-83b8-85e93110ea31 65D980Dec24252Eacb190E5Ba9Dde4F1 dv
{'plan_code': '2ilFzpR', 'user_email': 'fengaiqin@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
nE32vqA_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select BACsqaM
Could not find a project named 'BACsqaM'
BACsqaM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project BACsqaM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir acdacfc7-6e02-4c89-a1f0-2fedce4d2398:/2ilFzpR20201211180259
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/2ilFzpR/result/upload acdacfc7-6e02-4c89-a1f0-2fedce4d2398:/2ilFzpR20201211180259/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p nE32vqA_Online1 -d 90 E2B8030288F814C4C6Ac0Dc26Fa76C67
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p acdacfc7-6e02-4c89-a1f0-2fedce4d2398 E2B8030288F814C4C6Ac0Dc26Fa76C67 dv
{'plan_code': '9xAe6Dw', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
wyGtHNoc_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SumxM
Could not find a project named '16SumxM'
16SumxM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SumxM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir bb7d1edd-0da0-46fe-889f-cd9a4dec6433:/9xAe6Dw20201214112837
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/9xAe6Dw/result/upload bb7d1edd-0da0-46fe-889f-cd9a4dec6433:/9xAe6Dw20201214112837/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p wyGtHNoc_Online1 -d 90 Dca019188C916255B4E66E5Fdd3D127E
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p bb7d1edd-0da0-46fe-889f-cd9a4dec6433 Dca019188C916255B4E66E5Fdd3D127E dv
{'plan_code': 'QDlZ69x', 'user_email': 'dongzhsh@genomics.cn'}
{'plan_code': '2VrWQnR', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
wyGtHNoc_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SumxM
Setting current project to: 16SumxM
16SumxM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir bb7d1edd-0da0-46fe-889f-cd9a4dec6433:/QDlZ69x20201214143403
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/QDlZ69x/result/upload bb7d1edd-0da0-46fe-889f-cd9a4dec6433:/QDlZ69x20201214143403/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p wyGtHNoc_Online1 -d 90 Dca019188C916255B4E66E5Fdd3D127E
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p bb7d1edd-0da0-46fe-889f-cd9a4dec6433 Dca019188C916255B4E66E5Fdd3D127E dv
{'plan_code': 'RItOPvF', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
3tictF0J_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SipxM_16SyruM_16SamtM
Could not find a project named '16SipxM_16SyruM_16SamtM'
16SipxM_16SyruM_16SamtM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SipxM_16SyruM_16SamtM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/2VrWQnR20201214143449
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/2VrWQnR/result/upload aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/2VrWQnR20201214143449/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 3tictF0J_Online1 -d 90 D47F8D7Ff82F32Bb2E73532Dad0Beeca
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p aaa4e0f3-0910-4837-b4f0-d6b9b5f01130 D47F8D7Ff82F32Bb2E73532Dad0Beeca dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
3tictF0J_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SipxM_16SyruM_16SamtM
Setting current project to: 16SipxM_16SyruM_16SamtM
16SipxM_16SyruM_16SamtM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/RItOPvF20201214143840
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/RItOPvF/result/upload aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/RItOPvF20201214143840/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 3tictF0J_Online1 -d 90 D47F8D7Ff82F32Bb2E73532Dad0Beeca
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p aaa4e0f3-0910-4837-b4f0-d6b9b5f01130 D47F8D7Ff82F32Bb2E73532Dad0Beeca dv
{'plan_code': 'jFigGhE', 'user_email': 'fengaiqin@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
fXsKGbcD_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MICcqjM_MICjykM
Could not find a project named 'MICcqjM_MICjykM'
MICcqjM_MICjykM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MICcqjM_MICjykM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 0ebb336d-330d-494c-a2fb-b13a962727dc:/jFigGhE20201214175708
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/jFigGhE/result/upload 0ebb336d-330d-494c-a2fb-b13a962727dc:/jFigGhE20201214175708/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p fXsKGbcD_Online1 -d 90 310D47A2C6B0F39Af62Cce07016E87D8
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 0ebb336d-330d-494c-a2fb-b13a962727dc 310D47A2C6B0F39Af62Cce07016E87D8 dv
{'plan_code': 'zoaBrJP', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
od7LIM9_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16ShvlM
Setting current project to: 16ShvlM
16ShvlM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir f6ac60a9-0aa9-4584-96df-0dc2c53fdb20:/zoaBrJP20201214181055
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/zoaBrJP/result/upload f6ac60a9-0aa9-4584-96df-0dc2c53fdb20:/zoaBrJP20201214181055/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p od7LIM9_Online1 -d 90 58A2Afd2Fc9453F308A9521A4719800E
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p f6ac60a9-0aa9-4584-96df-0dc2c53fdb20 58A2Afd2Fc9453F308A9521A4719800E dv
{'plan_code': '6FiIHKA', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
L7AIYgG_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select SHExatM_SHEmifM
Could not find a project named 'SHExatM_SHEmifM'
SHExatM_SHEmifM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project SHExatM_SHEmifM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir eb9837aa-414d-4010-bc30-b0c3dbe2d5a2:/6FiIHKA20201215085453
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/6FiIHKA/result/upload eb9837aa-414d-4010-bc30-b0c3dbe2d5a2:/6FiIHKA20201215085453/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p L7AIYgG_Online1 -d 90 B097Cfd3988577F2C00A8Fff546Bfb31
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p eb9837aa-414d-4010-bc30-b0c3dbe2d5a2 B097Cfd3988577F2C00A8Fff546Bfb31 dv
{'plan_code': 'p2l4lNQ', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
WGKY6r8f8QM_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SqsxM
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 205, in APIRequest
    raise exceptions.APIError(url, response.json())
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
retry 1 times , 10s later
retry 2 times , 20s later
retry 3 times , 30s later
retry 4 times , 40s later
retry 5 times , 50s later
Traceback (most recent call last):
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/cli/__init__.py", line 127, in _list_user_projects
    projects = bgionline.api.user_projects()
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/api.py", line 64, in user_projects
    always_retry=always_retry, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/bgionline/__init__.py", line 205, in APIRequest
    raise exceptions.APIError(url, response.json())
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/Software/miniconda3/envs/qiime1/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
bo updating... or Other error; Exit()
{'plan_code': 'p2l4lNQ', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
WGKY6r8f8QM_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SqsxM
Could not find a project named '16SqsxM'
16SqsxM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SqsxM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 1292715a-a3a3-4ddc-aba8-90404b2bef60:/p2l4lNQ20201215165606
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/p2l4lNQ/result/upload 1292715a-a3a3-4ddc-aba8-90404b2bef60:/p2l4lNQ20201215165606/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p WGKY6r8f8QM_Online1 -d 90 866573Bd08Be295A9403886F8A6A2615
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 1292715a-a3a3-4ddc-aba8-90404b2bef60 866573Bd08Be295A9403886F8A6A2615 dv
{'plan_code': 'oHTjUti', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
kacKB0D_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METikaM
Setting current project to: METikaM
METikaM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 070bd88b-9b94-48ad-8304-405433e1b9a0:/oHTjUti20201216100842
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/oHTjUti/result/upload 070bd88b-9b94-48ad-8304-405433e1b9a0:/oHTjUti20201216100842/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p kacKB0D_Online1 -d 90 027B2Afd58Bb088Ee9B85E3A2Be1234C
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 070bd88b-9b94-48ad-8304-405433e1b9a0 027B2Afd58Bb088Ee9B85E3A2Be1234C dv
nohup: ignoring input
{'plan_code': 'w05ZxYr', 'user_email': 'shijiamei@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
w1nnmU9B6PZ_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V4fwfM
Could not find a project named 'V4fwfM'
V4fwfM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project V4fwfM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir f90eefa6-d83d-439a-9b2c-099cdea0de17:/w05ZxYr20201216105619
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/w05ZxYr/result/upload f90eefa6-d83d-439a-9b2c-099cdea0de17:/w05ZxYr20201216105619/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p w1nnmU9B6PZ_Online1 -d 90 Fb174Ee76Bd9F26514A737427Ade069B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p f90eefa6-d83d-439a-9b2c-099cdea0de17 Fb174Ee76Bd9F26514A737427Ade069B dv
{'plan_code': 'L6pU0Vt', 'user_email': 'dongzhsh@genomics.cn'}
{'plan_code': 'JfbsLim', 'user_email': 'dongzhsh@genomics.cn'}
{'plan_code': '1O9AGy5', 'user_email': 'dongzhsh@genomics.cn'}
{'plan_code': '5Gxuh2b', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RwhUIzb_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SbxnM
Could not find a project named '16SbxnM'
16SbxnM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SbxnM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/L6pU0Vt20201216132627
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/L6pU0Vt/result/upload 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/L6pU0Vt20201216132627/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RwhUIzb_Online1 -d 90 Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 6e2e9117-fb79-454c-b2ac-4d5b818be37b Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017 dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RwhUIzb_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SbxnM
Setting current project to: 16SbxnM
16SbxnM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/JfbsLim20201216132642
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/JfbsLim/result/upload 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/JfbsLim20201216132642/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RwhUIzb_Online1 -d 90 Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 6e2e9117-fb79-454c-b2ac-4d5b818be37b Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017 dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RwhUIzb_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SbxnM
Setting current project to: 16SbxnM
16SbxnM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/5Gxuh2b20201216132658
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/5Gxuh2b/result/upload 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/5Gxuh2b20201216132658/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RwhUIzb_Online1 -d 90 Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 6e2e9117-fb79-454c-b2ac-4d5b818be37b Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017 dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
RwhUIzb_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SbxnM
Setting current project to: 16SbxnM
16SbxnM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/1O9AGy520201216132649
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/1O9AGy5/result/upload 6e2e9117-fb79-454c-b2ac-4d5b818be37b:/1O9AGy520201216132649/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p RwhUIzb_Online1 -d 90 Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 6e2e9117-fb79-454c-b2ac-4d5b818be37b Bcbbc0E6D7Fc5Fc7Eddf2Bf7F18Ec017 dv
{'plan_code': 'eeW9KDb', 'user_email': 'liangliping@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@16s1:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
xMIWTPSS_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METfajM
retry 1 times , 10s later
retry 1 times , 10s later
bo updating... or Other error; Exit()
Traceback (most recent call last):
  File "run_boupload.py", line 67, in <module>
    rab.receieve()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 81, in receieve
    self.channel.start_consuming()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 513, in _flush_output
    self._impl.ioloop.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 576, in poll
    self._poller.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1181, in poll
    events = self._poll.poll(self._get_max_wait())
KeyboardInterrupt
nohup: ignoring input
{'plan_code': 'eeW9KDb', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
{'plan_code': '2cOoHFd', 'user_email': 'zhuhui1@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
{'plan_code': '2cOoHFd', 'user_email': 'zhuhui1@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
{'plan_code': 'eeW9KDb', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
Traceback (most recent call last):
  File "run_boupload.py", line 67, in <module>
    rab.receieve()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 81, in receieve
    self.channel.start_consuming()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 513, in _flush_output
    self._impl.ioloop.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 576, in poll
    self._poller.poll()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1181, in poll
    events = self._poll.poll(self._get_max_wait())
KeyboardInterrupt
nohup: ignoring input
{'plan_code': 'eeW9KDb', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': 'eeW9KDb', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': '2cOoHFd', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
xMIWTPSS_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METfajM
retry 1 times , 10s later
retry 2 times , 20s later
retry 1 times , 10s later
retry 2 times , 20s later
bo updating... or Other error; Exit()
{'plan_code': 'eeW9KDb', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
xMIWTPSS_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METfajM
Setting current project to: METfajM
METfajM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir eb8be332-aea6-46ce-8bec-8fc72691d1bf:/eeW9KDb20201221142651
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/eeW9KDb/result/upload eb8be332-aea6-46ce-8bec-8fc72691d1bf:/eeW9KDb20201221142651/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p xMIWTPSS_Online1 -d 90 591B3Ff4B3Fa6D0E4309D45F4Ecdda7C
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p eb8be332-aea6-46ce-8bec-8fc72691d1bf 591B3Ff4B3Fa6D0E4309D45F4Ecdda7C dv
{'plan_code': '0CLpRyb', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
{'plan_code': '0CLpRyb', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
3tictF0J_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SipxM_16SyruM_16SamtM
Setting current project to: 16SipxM_16SyruM_16SamtM
16SipxM_16SyruM_16SamtM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/0CLpRyb20201222182252
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/0CLpRyb/result/upload aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/0CLpRyb20201222182252/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 3tictF0J_Online1 -d 90 D47F8D7Ff82F32Bb2E73532Dad0Beeca
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p aaa4e0f3-0910-4837-b4f0-d6b9b5f01130 D47F8D7Ff82F32Bb2E73532Dad0Beeca dv
{'plan_code': 'KGIIJyx', 'user_email': 'dongzhsh@genomics.cn'}
{'plan_code': 'Csxt5UI', 'user_email': 'dongzhsh@genomics.cn'}
{'plan_code': 'aHKxVZ5', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
DE1laH0_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SocbM_16ShniM
Setting current project to: 16SocbM_16ShniM
16SocbM_16ShniM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 8e3cdd69-a483-4d8b-9721-eeb4aa39a418:/aHKxVZ520201222182752
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/aHKxVZ5/result/upload 8e3cdd69-a483-4d8b-9721-eeb4aa39a418:/aHKxVZ520201222182752/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p DE1laH0_Online1 -d 90 71319B68E583A58685702B43F3Ec7Ba0
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 8e3cdd69-a483-4d8b-9721-eeb4aa39a418 71319B68E583A58685702B43F3Ec7Ba0 dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
DE1laH0_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SocbM_16ShniM
Could not find a project named '16SocbM_16ShniM'
16SocbM_16ShniM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project 16SocbM_16ShniM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 8e3cdd69-a483-4d8b-9721-eeb4aa39a418:/KGIIJyx20201222182728
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/KGIIJyx/result/upload 8e3cdd69-a483-4d8b-9721-eeb4aa39a418:/KGIIJyx20201222182728/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p DE1laH0_Online1 -d 90 71319B68E583A58685702B43F3Ec7Ba0
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 8e3cdd69-a483-4d8b-9721-eeb4aa39a418 71319B68E583A58685702B43F3Ec7Ba0 dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
DE1laH0_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SocbM_16ShniM
Setting current project to: 16SocbM_16ShniM
16SocbM_16ShniM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 8e3cdd69-a483-4d8b-9721-eeb4aa39a418:/Csxt5UI20201222182742
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/Csxt5UI/result/upload 8e3cdd69-a483-4d8b-9721-eeb4aa39a418:/Csxt5UI20201222182742/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p DE1laH0_Online1 -d 90 71319B68E583A58685702B43F3Ec7Ba0
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 8e3cdd69-a483-4d8b-9721-eeb4aa39a418 71319B68E583A58685702B43F3Ec7Ba0 dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
3tictF0J_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SipxM_16SyruM_16SamtM
Setting current project to: 16SipxM_16SyruM_16SamtM
16SipxM_16SyruM_16SamtM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/0CLpRyb20201222182704
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/0CLpRyb/result/upload aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/0CLpRyb20201222182704/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 3tictF0J_Online1 -d 90 D47F8D7Ff82F32Bb2E73532Dad0Beeca
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p aaa4e0f3-0910-4837-b4f0-d6b9b5f01130 D47F8D7Ff82F32Bb2E73532Dad0Beeca dv
{'plan_code': 'MFJSnMu', 'user_email': 'P_Micro_Bioanalysis@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
DqKw7h0v_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select MUSeatM
Could not find a project named 'MUSeatM'
MUSeatM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project MUSeatM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 7be9eba3-2c74-4658-bc5e-85d42f304342:/MFJSnMu20201223084428
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/MFJSnMu/result/upload 7be9eba3-2c74-4658-bc5e-85d42f304342:/MFJSnMu20201223084428/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p DqKw7h0v_Online1 -d 90 48Bf6F21709C2Bc72Dc29D5D7Ae691E2
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 7be9eba3-2c74-4658-bc5e-85d42f304342 48Bf6F21709C2Bc72Dc29D5D7Ae691E2 dv
Traceback (most recent call last):
  File "run_boupload.py", line 67, in <module>
    rab.receieve()
  File "/root/16s/Modules_v2/Bo_upload/../SimplePipe/myRabbitMQ.py", line 81, in receieve
    self.channel.start_consuming()
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
    self._flush_output(common_terminator)
  File "/root/Software/miniconda3/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.ConnectionClosedByBroker: (320, "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'")
{'plan_code': 'Tmgyljx', 'user_email': 'dongzhsh@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
3tictF0J_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select 16SipxM_16SyruM_16SamtM
Setting current project to: 16SipxM_16SyruM_16SamtM
16SipxM_16SyruM_16SamtM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/Tmgyljx20201223164916
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/Tmgyljx/result/upload aaa4e0f3-0910-4837-b4f0-d6b9b5f01130:/Tmgyljx20201223164916/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p 3tictF0J_Online1 -d 90 D47F8D7Ff82F32Bb2E73532Dad0Beeca
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p aaa4e0f3-0910-4837-b4f0-d6b9b5f01130 D47F8D7Ff82F32Bb2E73532Dad0Beeca dv
{'plan_code': 'u7vlf4T', 'user_email': 'zhoudandan@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
q2zCfBLM6rH_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select SOIlfuM_SOIzmwM
Could not find a project named 'SOIlfuM_SOIzmwM'
SOIlfuM_SOIzmwM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project SOIlfuM_SOIzmwM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 938a3c97-df58-4de9-a9b5-430ea4957939:/u7vlf4T20201224162636
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/u7vlf4T/result/upload 938a3c97-df58-4de9-a9b5-430ea4957939:/u7vlf4T20201224162636/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p q2zCfBLM6rH_Online1 -d 90 53F5E44713Af8C02C80B16Cc8983F291
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 938a3c97-df58-4de9-a9b5-430ea4957939 53F5E44713Af8C02C80B16Cc8983F291 dv
{'plan_code': 'OsmCbXO', 'user_email': 'shijiamei@genomics.cn'}
{'plan_code': 'OsmCbXO', 'user_email': 'shijiamei@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
GpgfOj7n_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3VyqqM
Could not find a project named 'V3VyqqM'
V3VyqqM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project V3VyqqM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir be766ec5-3010-41f4-beb6-a0cea1e4ce98:/OsmCbXO20201225094042
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/OsmCbXO/result/upload be766ec5-3010-41f4-beb6-a0cea1e4ce98:/OsmCbXO20201225094042/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p GpgfOj7n_Online1 -d 90 772025118B8981Aba0E0F24512118A8B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p be766ec5-3010-41f4-beb6-a0cea1e4ce98 772025118B8981Aba0E0F24512118A8B dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
GpgfOj7n_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3VyqqM
Setting current project to: V3VyqqM
V3VyqqM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir be766ec5-3010-41f4-beb6-a0cea1e4ce98:/OsmCbXO20201225094104
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/OsmCbXO/result/upload be766ec5-3010-41f4-beb6-a0cea1e4ce98:/OsmCbXO20201225094104/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p GpgfOj7n_Online1 -d 90 772025118B8981Aba0E0F24512118A8B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p be766ec5-3010-41f4-beb6-a0cea1e4ce98 772025118B8981Aba0E0F24512118A8B dv
{'plan_code': 'Xwwjmtd', 'user_email': 'shijiamei@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
LmRK06qD5_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select V3VazcM
Could not find a project named 'V3VazcM'
V3VazcM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project V3VazcM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 98842115-7076-4057-8cdf-a17ea8b623dd:/Xwwjmtd20201225094724
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/Xwwjmtd/result/upload 98842115-7076-4057-8cdf-a17ea8b623dd:/Xwwjmtd20201225094724/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p LmRK06qD5_Online1 -d 90 35691E0F2014158058Ae61570132721C
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 98842115-7076-4057-8cdf-a17ea8b623dd 35691E0F2014158058Ae61570132721C dv
{'plan_code': 'lZiiAn1', 'user_email': 'fengaiqin@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
ttrXbfs_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select METtctM
Could not find a project named 'METtctM'
METtctM need to be created
/root/Software/miniconda3/envs/qiime1/bin/bo new project METtctM
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 79595d45-9ee1-42e0-8903-f155b128adb1:/lZiiAn120201225095411
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/lZiiAn1/result/upload 79595d45-9ee1-42e0-8903-f155b128adb1:/lZiiAn120201225095411/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p ttrXbfs_Online1 -d 90 1F1D901Bf04D7Bc15Ad1Eea6Fad4131B
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 79595d45-9ee1-42e0-8903-f155b128adb1 1F1D901Bf04D7Bc15Ad1Eea6Fad4131B dv
{'plan_code': '2cOoHFd', 'user_email': 'zhuhui1@genomics.cn'}
{'plan_code': '2cOoHFd', 'user_email': 'zhuhui1@genomics.cn'}
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
iR7Pxn8ps4z_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select ITSnxjM_METiddM
Setting current project to: ITSnxjM_METiddM
ITSnxjM_METiddM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 77a4c771-5616-4ac1-b892-84786f6f89f9:/2cOoHFd20201225110123
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/2cOoHFd/result/upload 77a4c771-5616-4ac1-b892-84786f6f89f9:/2cOoHFd20201225110123/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p iR7Pxn8ps4z_Online1 -d 90 441E5217B898C3634Ee41969977018Ee
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 77a4c771-5616-4ac1-b892-84786f6f89f9 441E5217B898C3634Ee41969977018Ee dv
Acquiring Base Information
search mongo
mongodb://root:BgiMicrobe%402020@8.129.234.13:27017,16s2:27017,16s3:27017
connect mongo successful......
search mysql
connect mysql......
connect mysql successful......
Base Parser
Upload Main......
/root/Software/miniconda3/envs/qiime1/bin/bo login --token 8HX5tDVZIDraS8OS9XSQuTbtaTddT3Qs --noprojects
iR7Pxn8ps4z_Online1
/root/Software/miniconda3/envs/qiime1/bin/bo select ITSnxjM_METiddM
Setting current project to: ITSnxjM_METiddM
ITSnxjM_METiddM have existed
/root/Software/miniconda3/envs/qiime1/bin/bo find project
/root/Software/miniconda3/envs/qiime1/bin/bo mkdir 77a4c771-5616-4ac1-b892-84786f6f89f9:/2cOoHFd20201225110142
/root/Software/miniconda3/envs/qiime1/bin/bo upload -c 5 -f /nas1/production_16s/analysis/report/2cOoHFd/result/upload 77a4c771-5616-4ac1-b892-84786f6f89f9:/2cOoHFd20201225110142/
/root/Software/miniconda3/envs/qiime1/bin/bo new delivery_user -p iR7Pxn8ps4z_Online1 -d 90 441E5217B898C3634Ee41969977018Ee
/root/Software/miniconda3/envs/qiime1/bin/bo set_permission -p 77a4c771-5616-4ac1-b892-84786f6f89f9 441E5217B898C3634Ee41969977018Ee dv
